### ISSUE TITLE
Неверное указано слово "чтобы" в плейсхолдере строки поиска

### ISSUE THREAD

**Issue by svifty7** [TTG-Club/ttg-club-frontend#125]
**Шаги для воспроизведения:**

1. Загрузить сайт ttg.club
2. Нажать кнопку Поиск

**Результат**: В строке поиска имеется плейсхолдер "Введите текст, что бы начать", где слова "что бы" указаны раздельно.
**Ожидаемый результат**: Слово "чтобы" в поисковой строке должно быть указано слитно.

Ошибка актуальна для страницы поиска https://ttg.club/search?search=&page=1

**Операционная система:**
macOS Monterey Version 12.6 (21G115)
**Браузер:**
Safari Version 15.6.1 (17613.3.9.1.16)
**Разрешение экрана в браузере при котором был обнаружен баг (ширина × высота):** 1680 × 906
**Ссылка на страницу с багом:**
https://ttg.club/

**Скрин бага:**
![IMAGE 2023-03-07 19:00:37](https://user-images.githubusercontent.com/126567491/223477446-a6952f55-b6cc-4190-bd52-4ee32f29344d.jpg)

author: @MaksimLapatko

**Comment by olegvolkov91** [comment]
поправил
